# Generated by Django 4.0 on 2022-01-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_orderitem_replacement_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='replacement_product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='replaced_with',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_with', to='api.product'),
        ),
    ]
